stages:
  - build
  - lint
  - test
  - publish
  - workflow

variables:
  PRE_COMMIT_VERSION: "2.17.0"
  PROJECT_NAME: biondeep_ig
  DOCKER_IMAGE_NAME: registry.gitlab.com/instadeep/biondeep-ig

.docker_login: &docker_login |
  docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

build_image:
  image: eu.gcr.io/int-infra-harborbackup-gcp/docker-hub/docker:19.03
  services:
    - eu.gcr.io/int-infra-harborbackup-gcp/docker-hub/docker:19.03-dind
  stage: build
  script:
    - *docker_login
    - apk add --no-cache git
    - apk add --no-cache make
    - make build-ci
    - make push-ci

linters:
  image: $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  stage: lint
  script:
    - pip install pre-commit==$PRE_COMMIT_VERSION
    - pre-commit install -t pre-commit
    - pre-commit run --all-files

test:
  image: $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  stage: test
  script:
    - pytest --cov=$PROJECT_NAME --cov-report=term-missing --junit-xml=test-results.xml
      --doctest-modules -vv
    - coverage html --directory=coverage_html_report
    - coverage report
  coverage: '/TOTAL.+ (\d+\.?\d+)%/'
  artifacts:
    name: "Test Results"
    when: always
    paths:
      - ./test-results.xml
      - ./coverage_html_report
    reports:
      junit: ./test-results.xml
    expire_in: 1 day

pages:
  image: $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  stage: publish
  needs: ["build_image"]
  script:
    - pip install -r $CI_PROJECT_DIR/requirements.txt
    - mkdocs build --verbose
  artifacts:
    paths:
      - public
  only:
    - main

run-pmhc-argoWorkflow:
  stage: workflow
  image: registry.gitlab.com/instadeep/multi_bin_packing/ci:latest
  when: manual
  needs:
    - job: build_image
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /ARGO .*/
  tags:
    - k8s-biondeep-ig
  script:
    - yq e ".metadata.name = \"pmhc-$CI_COMMIT_SHORT_SHA\"" -i
      ./biondeep_ig/bio_ig_gen/pipeline/argo/pmhc-gen-workflow.yaml
    - yq e ".spec.arguments.parameters[0].value = \"$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA\"" -i
      ./biondeep_ig/bio_ig_gen/pipeline/argo/pmhc-gen-workflow.yaml
    - kubectl apply -f ./biondeep_ig/bio_ig_gen/pipeline/argo/pmhc-gen-workflow.yaml --namespace
      biondeep-ig-infra
    - echo "To see the logs, Please visit Argo Server
      https://argo.instadeep.ichorai.io/workflows/biondeep-ig-infra"

run-tcr-pmhc-argoWorkflow:
  stage: workflow
  image: registry.gitlab.com/instadeep/multi_bin_packing/ci:latest
  when: manual
  needs:
    - job: build_image
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /ARGO .*/
  tags:
    - k8s-biondeep-ig
  script:
    - yq e ".metadata.name = \"tcr-pmhc-$CI_COMMIT_SHORT_SHA\"" -i
      ./biondeep_ig/bio_ig_gen/pipeline/argo/tcr-pmhc-gen-workflow.yaml
    - yq e ".spec.arguments.parameters[0].value = \"$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA\"" -i
      ./biondeep_ig/bio_ig_gen/pipeline/argo/tcr-pmhc-gen-workflow.yaml
    - kubectl apply -f ./biondeep_ig/bio_ig_gen/pipeline/argo/tcr-pmhc-gen-workflow.yaml --namespace
      biondeep-ig-infra
    - echo "To see the logs, Please visit Argo Server
      https://argo.instadeep.ichorai.io/workflows/biondeep-ig-infra"
