stages:
  - build
  - lint
  - test

variables:
  PRE_COMMIT_VERSION: "2.17.0"
  PROJECT_NAME: biondeep_ig
  DOCKER_IMAGE_NAME: registry.gitlab.com/instadeep/biondeep-ig
  DOCKER_HOME_DIRECTORY: /home/app

.docker_login: &docker_login |
  docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

build_image:
  image: eu.gcr.io/int-infra-harborbackup-gcp/docker-hub/docker:19.03
  services:
    - eu.gcr.io/int-infra-harborbackup-gcp/docker-hub/docker:19.03-dind
  stage: build
  script:
    - *docker_login
    - apk add --no-cache git
    - apk add --no-cache make
    - make build-ci
    - make push-ci

linters:
  image: $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  stage: lint
  script:
    - cd $DOCKER_HOME_DIRECTORY
    - pip install pre-commit==$PRE_COMMIT_VERSION
    # hack to be able to use pre-commit without all the .git directory available in the docker
    # cf https://github.com/pre-commit/pre-commit/issues/1152
    - git init .
    - pre-commit install -t pre-commit
    - pre-commit run --all-files

test:
  image: $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  stage: test
  script:
    - cd $DOCKER_HOME_DIRECTORY
    - pytest --cov=$PROJECT_NAME --cov-report=term-missing --junit-xml=test-results.xml
      --doctest-modules -vv
    - coverage html --directory=coverage_html_report
    - coverage report
  coverage: '/TOTAL.+ (\d+\.?\d+)%/'
  artifacts:
    name: "Test Results"
    when: always
    paths:
      - ./test-results.xml
      - ./coverage_html_report
    reports:
      junit: ./test-results.xml
    expire_in: 1 day
