stages:
  - build
  - lint
  - test
  - deploy
  - publish

variables:
  PRE_COMMIT_VERSION: "3.5.0"

  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_PREVIOUS: $CI_REGISTRY_IMAGE:$CI_COMMIT_BEFORE_SHA
  DOCKER_IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest

  DOCKER_IMAGE_NAME_LINT: $CI_REGISTRY_IMAGE/lint
  DOCKER_IMAGE_LINT: $DOCKER_IMAGE_NAME_LINT:$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_PREVIOUS_LINT: $DOCKER_IMAGE_NAME_LINT:$CI_COMMIT_BEFORE_SHA
  DOCKER_IMAGE_LATEST_LINT: $DOCKER_IMAGE_NAME_LINT:latest

  DOCKER_IMAGE_NAME_DOCS: $CI_REGISTRY_IMAGE/docs
  DOCKER_IMAGE_DOCS: $DOCKER_IMAGE_NAME_DOCS:$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_PREVIOUS_DOCS: $DOCKER_IMAGE_NAME_DOCS:$CI_COMMIT_BEFORE_SHA
  DOCKER_IMAGE_LATEST_DOCS: $DOCKER_IMAGE_NAME_DOCS:latest

.docker-login:
  image: eu.gcr.io/int-infra-harborbackup-gcp/docker-hub/docker:19.03
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD

build-image:
  extends: .docker-login
  stage: build
  tags:
    - node080-autoscaled-kubernetes-internal
  script:
    - docker pull $DOCKER_IMAGE_PREVIOUS || docker pull $DOCKER_IMAGE_LATEST || true
    - docker build --cache-from $DOCKER_IMAGE_PREVIOUS --cache-from $DOCKER_IMAGE_LATEST -t
      $DOCKER_IMAGE  .
    - docker push $DOCKER_IMAGE

build-lint:
  extends: .docker-login
  stage: build
  tags:
    - node080-autoscaled-kubernetes-internal
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - docker pull $DOCKER_IMAGE_PREVIOUS_LINT || docker pull $DOCKER_IMAGE_LATEST_LINT || true
    - docker build --cache-from $DOCKER_IMAGE_PREVIOUS_LINT --cache-from $DOCKER_IMAGE_LATEST_LINT
      -t $DOCKER_IMAGE_LINT . -f Dockerfile.lint
    - docker push $DOCKER_IMAGE_LINT
build-docs:
  extends: .docker-login
  stage: build
  tags:
    - node080-autoscaled-kubernetes-internal
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - docker pull $DOCKER_IMAGE_PREVIOUS_DOCS || docker pull $DOCKER_IMAGE_LATEST_DOCS || true
    - docker build --cache-from $DOCKER_IMAGE_PREVIOUS_DOCS --cache-from $DOCKER_IMAGE_LATEST_DOCS
      -t $DOCKER_IMAGE_DOCS . -f Dockerfile.docs
    - docker push $DOCKER_IMAGE_DOCS
lint:
  image: $DOCKER_IMAGE_LINT
  stage: lint
  tags:
    - node080-autoscaled-kubernetes-internal
  needs: [build-lint]
  script:
    - pre-commit run --all-files

pytest:
  image: $DOCKER_IMAGE
  needs: [build-image]
  stage: test
  tags:
    - node080-autoscaled-kubernetes-internal
  script:
    - apt-get install zip unzip
    - export stage=test
    # - unzip  tests/fixtures/model-fixtures.zip -d tests/models
    # - cp -r tests/models/model-fixtures/* tests/models/
    # - rm -r tests/models/model-fixtures/
    # - rm tests/fixtures/model-fixtures.zip
    - pytest --cov=ig --cov-report=term-missing --junit-xml=test-results.xml --doctest-modules -vv
    - coverage html --directory=coverage_html_report
    - coverage report
  coverage: '/TOTAL.+ (\d+\.?\d+)%/'
  artifacts:
    name: "Test Results"
    when: always
    paths:
      - .test-results.xml
      - .coverage_html_report
    reports:
      junit: .test-results.xml
    expire_in: 1 day

test-pages:
  image: $DOCKER_IMAGE_DOCS
  stage: test
  tags:
    - node080-autoscaled-kubernetes-internal
  needs: [build-docs]
  script:
    - mkdocs build --verbose --site-dir docs_public
  artifacts:
    paths:
      - docs_public

pages:
  image: $DOCKER_IMAGE_DOCS
  stage: publish
  tags:
    - node080-autoscaled-kubernetes-internal
  needs: [build-docs, test-pages]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - mkdocs build --verbose
  artifacts:
    paths:
      - public

push-latest-ig:
  extends: .docker-login
  stage: deploy
  tags:
    - node080-autoscaled-kubernetes-internal
  needs:
    - job: build-image

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - docker pull $DOCKER_IMAGE
    - docker tag $DOCKER_IMAGE $DOCKER_IMAGE_LATEST
    - docker push $DOCKER_IMAGE_LATEST

push-latest-doc:
  extends: .docker-login
  stage: deploy
  tags:
    - node080-autoscaled-kubernetes-internal
  needs:
    - job: build-docs

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - docker pull $DOCKER_IMAGE_DOCS
    - docker tag $DOCKER_IMAGE_DOCS $DOCKER_IMAGE_LATEST_DOCS
    - docker push $DOCKER_IMAGE_LATEST_DOCS

push-latest-lint:
  extends: .docker-login
  stage: deploy
  tags:
    - node080-autoscaled-kubernetes-internal
  needs:
    - job: build-docs

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - docker pull $DOCKER_IMAGE_LINT
    - docker tag $DOCKER_IMAGE_LINT $DOCKER_IMAGE_LATEST_LINT
    - docker push $DOCKER_IMAGE_LATEST_LINT
