ARG TAG=latest
FROM registry.gitlab.com/instadeep/biondeep-ig:$TAG

ARG host_uid
ARG host_gid
ENV USER=app

RUN apt-get update

RUN groupadd -f -g $host_gid  $USER
RUN useradd -r -m -u $host_uid -g $host_gid -o -s /bin/bash $USER
USER $USER

ENV PATH="/home/app/.local/bin:${PATH}"
ENV PATH=$PATH:/home/app/.local/bin
ENV PYTHONWARNINGS="ignore::UserWarning"

WORKDIR /home/$USER/ig
