kind: AIchorManifest
apiVersion: 0.2.1

builder:
  image: ig-ichor
  dockerfile: Dockerfile.AIchor
  context: .

spec:
  operator: tf
  image: ig-ichor
  # Update the command when necessary
  command: bash runAIchor_multi_train.sh # runAIchor.sh or runAIchor_multi_train.sh
  tensorboard:
    enabled: False

  types:
    Worker:
      count: 2
      resources:
        # Update the necessary resources
        # note that the number of cpus * ramRatio = number of gigabytes
        cpus: 4
        ramRatio: 6
