site_name: BioNDeep IG
site_description: BioNDeep IG data generation and training pipeline
site_author: bio-IG Contributors
site_url: https://instadeep.gitlab.io/biondeep-ig
site_dir: public
repo_name: instadeep/biondeep-ig
repo_url: https://gitlab.com/instadeep/biondeep-ig
docs_dir: docs/pages
strict: false
theme:
  name: material
  language: en
  palette:
    primary: md-primary-fg-color--dark
    accent: md-accent-fg-color
  icon:
    repo: fontawesome/brands/gitlab
  font:
    text: Avenir Next
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

markdown_extensions:
  - pymdownx.snippets:
      base_path: biondeep-structure
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - def_list
  - attr_list
  - footnotes
  - pymdownx.emoji

extra_javascript:
  - javascript/mathjax.js
  # These two javascript files load MathJax, c.f. https://www.mathjax.org/#gettingstarted.
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - git-revision-date
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
          selection:
            filters:
              - "!^test"
nav:
  - Home: index.md
  - IG:
      - Installation: ig/installation.md
      - Quickstart: ig/Quickstart.md
      - Data:
          - Overview: ig/data.md
          # - Data IG generation: ig/data_gen.md
          # - pMHC Data: ig/data_ig.md
          # - Generate peptide allele pairs: ig/generapte_peptide_allele.md
      - Commands:
          - Data processing:
              - configuration: ig/data_configuration.md
              - push pull GCP: ig/push_pull.md
              - processing command: ig/processing.md
          - Modeling:
              - configuration: ig/modeling_configuration.md
              - Feature selection: ig/FS.md
              - Train:
                  - Experiments: ig/experiments.md
                  - Models: ig/models.md
                  - Train: ig/train.md
                  - Inference: ig/eval.md
                  - Output: ig/layout.md
              - Multiple Train:
                  - Train: ig/multi_train.md
                  - Inference: ig/multi_inference.md
              - CIMT 2023: ig/cimt.md
              - Training with list of seeds and folds: ig/train_seed_fold.md
              - Hyper-parameters tuning: ig/tune.md
              - Ensemble: ig/ensembling.md
              - Comparison score: ig/comparison_score.md
              - Dai score ESM embeddings generation: ig/generate_esm_embedding.md
      - Contributing: ig/contributing.md
      - Changelog: ig/changelog.md
