model_type: LgbmModel
model_config:
  general_params:
    num_boost_round: 20000000
    early_stopping_rounds: 15
    verbose_eval: 20

  model_params:
    alpha: 0.02
    boosting: gbdt #could be gbdt, rf, dart, goss
    colsample_bytree: 1
    metric: ["auc", "binary_logloss"]
    max_depth: 7
    num_leaves: 31
    tree_learner: serial #serial , feature, data, voting
    num_threads: 16
    device_type: cpu
    force_col_wise: False
    force_row_wise: False
    deterministic: False
    min_data_in_leaf: 20
    min_child_weight: 19
    objective: binary # could be cross_entropy?
    seed: 2020
    subsample: 1
    learning_rate: 0.01
    verbosity: -1
