#!/bin/bash
# exit if any command fails
set -e

# arguments
while getopts a:b:o: param
do
    case "${param}" in
        a) CDR3A=${OPTARG};;
        b) CDR3B=${OPTARG};;
        o) OUTPUT_DIR=${OPTARG};;
        *) echo "Unknown flag." 1>&2 && exit 1
    esac
done

# replace cdr3a/b
ALPHA="AQTVTQSQPEMSVQEAETVTLSCTYDTSENDYILFWYKQPPSRQMILVIRQEAYKQQNATENRFSVNFQKAAKSFSLKISDSQLGDAAMYFCAYGEDDKIIFGKGTRLHILPNIQNPDPAVYQLRDSKSSDKSVCLFTDFDSQTNVSQSKDSDVYITDKCVLDMRSMDFKSNSAVAWSNKSDFACANAFNN"
ALPHA=${ALPHA//CAYGEDDKIIF/$CDR3A}
ALPHA=${ALPHA// /}

BETA="AEADIYQTPRYLVIGTGKKITLECSQTMGHDKMYWYQQDPGMELHLIHYSYGVNSTEKGDLSSESTVSRIRTEHFPLTLESARPSHTSQYLCASRRGSAELYFGPGTRLTVTEDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWWVNGKEVHSGVCTDPQPLKEQPALNDSRYALSSRLRVSATFWQDPRNHFRCQVQFYGLSENDEWTQDRAKPVTQIVSAEAWGRAA"
BETA=${BETA//CASRRGSAELYF/$CDR3B}
BETA=${BETA// /}

# use cdr3a/b to define suffix
suffix="$CDR3A-$CDR3B"
suffix=${suffix// /}

# call rosetta
/Rosetta/main/source/bin/tcrmodel.default.linuxgccrelease -alpha $ALPHA -beta $BETA -out:suffix $suffix -out:level 400 -out:pdb_gz -out:path:all $OUTPUT_DIR

# normal exit
exit 0
