neptune_logs: False
experiments:
  SingleModel:
    validation_column: validation
    plot_shap_values: False # False when using Logistic regression

label: cd4_any
benchmark_column:
  - prediction_average # prediction_average ,"mean_topk" ,"max_topk" ,"mintopk"
  - mean_topk
  - max_topk
  - min_topk

feature_paths:
  #- lr_cd4 # use this feature list for LR
  - Created_feature_list_Correlation_20_CD4
  - Created_feature_list_CosSimilarity_20_CD4
  - Created_feature_list_NormalizedStatistics_20_CD4
  - Created_feature_list_RFE_LR_20_CD4
  - Created_feature_list_RFE_XGBoost_20_CD4
  - Created_feature_list_RF_gini_20_CD4
  - Created_feature_list_SFM_LR_20_CD4
  - Created_feature_list_SFM_XGBoost_20_CD4

eval_id_name: patientid
observations_number: 20
comparison_score: tested_score_biondeep_mhci
print_evals: false
processing:
  isunlabelled: false
  fill_nan_method: keep
  seed: 1994
  validation_ratio: 0.1
  fold: 3
models:
  #- lgbm_config.yml
  - xgboost_config.yml
  #- catboost_config.yml
  #- LogisticRegression_config.yml
