model_type: RandomForestModel
model_config:
  general_params:
    verbose_eval: 10
  model_params:
    n_estimators: 100
    criterion: "gini"
    max_depth: 7
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: "sqrt"
    max_leaf_nodes: 20
    min_impurity_decrease: 0.0
