model_type: SupportVectorMachineModel
model_config:
  general_params:
    verbose_eval: False
  model_params:
    C: 1.0
    kernel: rbf
    degree: 3
    gamma: scale
    coef0: 0.0
    shrinking: True
    probability: False
    tol: 0.001
    cache_size: 200
    class_weight: "balanced"
    max_iter: -1
    decision_function_shape: ovr
    break_ties: False
    random_state: 1
