neptune_logs: False

experiments:
  SingleModel:
    validation_column: validation
    plot_shap_values: False
  KfoldExperiment:
    split_column: fold
    plot_shap_values: True
    plot_kfold_shap_values: True # False when using Logistic regression
    operation:
      - mean
      - max
      - min
      - median
    statics:
      - mean
      - max
      - min
label: cd8_any
feature_paths:
  - train_features
tuning:
  maximize: True
  nbr_trials: 1
processing:
  # process_data: False
  trainable_features: "features_quickstart.yml"
  validation_strategy: true
  isunlabelled: false
  fill_nan_method: keep
  seed: 20015
  validation_ratio: 0.1
  fold: 4
models:
  - tune_xgboost.yml
evaluation:
  print_evals: False
