experiments:
  Mut_AA:
    processing:
      trainable_features: features_pep.yml
      exclude_features:
        - ^diff.*mhci$
        - .*tested.*mhci$
        - ^diff.*whole$
        - .*tested.*whole$
        - tc3
  PredPep:
    processing:
      trainable_features: features_pep.yml
      exclude_features:
        - ^diff.*whole$
        - .*tested.*whole$
        - ^diff(?!.*(?:mhci|whole)$).*
        - ^mut|.*mut$
        - tc3

params:
  metrics:
    - topk
    - logloss
