neptune_logs: False
experiments:
  KfoldMultiSeedExperiment:
    split_column: fold
    plot_shap_values: False
    plot_kfold_shap_values: False # False when using Logistic regression
    model_seed: false
    split_seed: true
    nbr_seeds: 3
    print_seeds_evals: False
    save_seed_predictions: False
    seed_plot_fig: False
    operation:
      - mean
    statics:
      - mean
  KfoldExperiment:
    split_column: fold
    plot_shap_values: True
    plot_kfold_shap_values: True # False when using Logistic regression
    operation:
      - mean
    statics:
      - mean
  SingleModel:
    validation_column: validation
    plot_shap_values: True
label: cd8_any
processing:
  process_data: False
  remove_unnecessary_folders: False
  trainable_features: "features.yml"
  validation_strategy: false
  isunlabelled: false
  fill_nan_method: keep
  seed: 2023
  validation_ratio: 0.1
  fold: 5
models:
  - debug_xgboost_config.yml

evaluation:
  print_evals: True
  comparison_score: proxy_score_presentation
  threshold: 0.3
  metrics:
    - topk
    - roc
    - logloss
    - precision
    - recall
    - f1
  metric_selector: topk
  metrics_selector_higher: True
  data_name_selector: test # test , validation
  prediction_name_selector: "prediction_mean"
  monitoring_metrics:
    - roc
    - topk
    - logloss

FS:
  n_feat: 20
  keep_features_number: False
  separate_forced_features: False
  n_thread: 30
  FS_methods:
    - Fspca.yml
    - Fsxgboost.yml
