# model: Rostlab/prot_bert_bfd
# is_masked_model: False
# batch_size: 512
# workers: 8
model: InstaDeepAI/nucleotide-transformer-v2-50m-multi-species
is_masked_model: True # must be set to True for NT models
batch_size: 1
workers: 1
processing:
  drop_duplicates: True
  separate_tokens: True
  replace: True
  replace_pattern: "[UZOB]"
  replace_with: X
seq_columns:
  - wild_type
  - mutated
  # - tested_peptide
  # - wildtype_peptide
  # - tested_peptide_biondeep_mhci
  # - wildtype_peptide_biondeep_mhci
outputs:
  # - mean
  - cls
  # - raw
