model: Rostlab/prot_bert_bfd
is_masked_model: False
batch_size: 512
workers: 8
processing:
  drop_duplicates: True
  separate_tokens: True
  replace: True
  replace_pattern: "[UZOB]"
  replace_with: X
seq_columns:
  - tested_peptide
  - wildtype_peptide
  - tested_peptide_biondeep_mhci
  - wildtype_peptide_biondeep_mhci
outputs:
  - mean
  - cls
  - raw
