neptune_logs: False
experiments:
  KfoldExperiment:
    split_column: fold
    plot_shap_values: True
    plot_kfold_shap_values: True # False when using Logistic regression
    operation:
      - mean
      - max
      - min
      - median
    statics:
      - mean
      - max
      - min
  SingleModel:
    validation_column: validation
    plot_shap_values: True
label: cd8_any
feature_paths:
  - train_features
processing:
  process_data: False
  remove_proc_data: false
  trainable_features: features_float.biondeep_02_06_2022_transformer_public_v2
  # exclude_features:
  validation_strategy: true
  isunlabelled: false
  #normalizer:
  fill_nan_method: keep
  seeds: [1994, 2002]
  validation_ratio: 0.1
  folds: [5, 4, 6]
  nan_ratio: 0.6
  expression_name: geneexpression_final
  expression_column_name: expression

models:
  - xgboost_config.yml
evaluation:
  print_evals: True
  comparison_score: tested_score_biondeep_mhci
  # eval_id_name: patientid
  observations_number: 20
  threshold: 0.3
  metrics:
    - topk
    - roc
    - logloss
    - precision
    - recall
    - f1
  metric_selector: topk
  metrics_selector_higher: True
  data_name_selector: test # test , validation
  prediction_name_selector: "prediction_mean"
  monitoring_metrics:
    - roc
    - topk
    # - topk_20_patientid
    # - topk_patientid
