neptune_logs: False
experiments:
  KfoldExperiment:
    split_column: fold
    plot_shap_values: False
    plot_kfold_shap_values: False # False when using Logistic regression
    operation:
      - mean
      - max
      - min
      - median
    statics:
      - mean
      - max
      - min
  SingleModel:
    validation_column: validation
    plot_shap_values: False
label: cd8_any
feature_paths:
  - train_features
processing:
  remove_unnecessary_folders: False
  trainable_features: llm_based_features_config.yml
  # exclude_features:
  validation_strategy: true
  isunlabelled: false
  #normalizer:
  #normalizer_per_id:
  #normalizer_id: patientid
  fill_nan_method: keep
  seeds: [1994]
  validation_ratio: 0.1
  folds: [2]
  nan_ratio: 0.6

models:
  - llm_based_model_config.yml
evaluation:
  print_evals: True
  # eval_id_name: patientid
  observations_number: 20
  threshold: 0.3
  metrics:
    - topk
    - roc
    - logloss
    - precision
    - recall
    - f1
  metric_selector: topk
  metrics_selector_higher: True
  data_name_selector: test # test , validation
  prediction_name_selector: "prediction_mean"
  monitoring_metrics:
    - roc
    - topk
    # - topk_20_patientid
    # - topk_patientid
