neptune_logs: False
experiments:
  KfoldExperiment:
    split_column: fold
    plot_shap_values: True
    plot_kfold_shap_values: True # False when using Logistic regression
    operation:
      - mean
      - max
      - min
      - median
    statics:
      - mean
      - max
      - min
  SingleModel:
    validation_column: validation
    plot_shap_values: True
  DoubleKfold:
    split_column: fold
    statistics:
      - mean
      - max
      - min
    operation:
      - mean
      - max
      - min
      - median
label: cd8_any
feature_paths:
  - train_features
processing:
  remove_proc_data: false
  trainable_features: "features"
  #exclude_features:
  validation_strategy: True
  isunlabelled: false
  #normalizer:
  fill_nan_method: keep
  seed: 1994
  validation_ratio: 0.1
  fold: 5
models:
  - xgboost_config.yml
  - lgbm_config.yml

evaluation:
  print_evals: True
  comparison_score: presentation_score
  eval_id_name: patientid
  observations_number: 20
  threshold: 0.3
  metrics:
    - topk
    - roc
    - logloss
    - precision
    - recall
    - f1
  metric_selector: topk
  metrics_selector_higher: True
  data_name_selector: test # test , validation
  prediction_name_selector: "prediction_mean"
  monitoring_metrics:
    - roc
    - topk
    - topk_20_patientid
    - topk_patientid
FS:
  n_feat: 20
  force_features:
    - "tested_score_biondeep_mhci"
    - "expression"
    - "presentation_score"
  FS_methods:
    - Fspca.yml
    - Fsxgboost.yml
    - Fsxgboostshap.yml
    - Fsrfgini.yml
    - Fscossim.yml
    - Fscorr.yml
    - Fssfmlr.yml
    - Fsrfelr.yml
    - Fssfmxgboost.yml
    - Fsrfexgboost.yml
    - Fsrelief.yml
    - Fsmi.yml
    - Fsboruta.yml
